// Extracted verbatim from FEBELFIN CODA 2.6, Annexe II (Coding of the transactions).
//
// A CODA transaction code is 8 digits = type(1) + family(2) + transaction(2) + category(3).
// CODA_FAMILIES lists, per family, the 2-digit transaction codes split into debit/credit
// sections. CODA_CATEGORIES lists the 3-digit category codes (positions 6-8).
//
// Range / catch-all rows (e.g. "40-48 Codes proper to each bank", "49 Cancellation or
// correction", "90-98", "99") are preserved as-is with their literal code strings.

export interface CodaTransaction {
  code: string;
  direction: "debit" | "credit";
  description: string;
  comment?: string;
}

export interface CodaFamily {
  code: string;
  name: string;
  transactions: CodaTransaction[];
}

export const CODA_FAMILIES: CodaFamily[] = [
  {
    code: "01",
    name: "Domestic or local SEPA credit transfers",
    transactions: [
      {
        code: "01",
        direction: "debit",
        description: "Individual transfer order",
        comment:
          "Credit transfer given by the customer on paper or electronically, even if the execution date of this transfer is in the future. Domestic payments as well as euro payments meeting the requirements.",
      },
      {
        code: "02",
        direction: "debit",
        description: "Individual transfer order initiated by the bank",
        comment: "The bank takes the initiative for debiting the customer's account.",
      },
      {
        code: "03",
        direction: "debit",
        description: "Standing order",
        comment:
          "Credit transfer for which the order has been given once and which is carried out again at regular intervals without any change.",
      },
      {
        code: "05",
        direction: "debit",
        description: "Payment of wages, etc.",
        comment: "The principal will be debited for the total amount of the file entered.",
      },
      {
        code: "07",
        direction: "debit",
        description: "Collective transfer",
        comment: "The principal will be debited for the total amount of the file entered.",
      },
      {
        code: "13",
        direction: "debit",
        description: "Transfer from your account",
        comment:
          "Transfer from one account to another account of the same customer at the bank's or the customer's initiative (intracompany).",
      },
      {
        code: "17",
        direction: "debit",
        description: "Financial centralisation",
        comment:
          "In case of centralisation by the bank, type 2 will be allotted to this transaction. This total can be followed by the detailed movement.",
      },
      { code: "37", direction: "debit", description: "Costs" },
      {
        code: "39",
        direction: "debit",
        description: "Your issue circular cheque",
        comment: "To be used for issued circular cheques given in consignment",
      },
      { code: "40-48", direction: "debit", description: "Codes proper to each bank" },
      { code: "49", direction: "debit", description: "Cancellation or correction" },
      { code: "50", direction: "credit", description: "Transfer in your favour" },
      {
        code: "51",
        direction: "credit",
        description: "Transfer in your favour - initiated by the bank",
        comment: "The bank takes the initiative for crediting the customer's account.",
      },
      {
        code: "52",
        direction: "credit",
        description: "Payment in your favour",
        comment: "Payment by a third person",
      },
      { code: "54", direction: "credit", description: "Unexecutable transfer order" },
      { code: "60", direction: "credit", description: "Non-presented circular cheque" },
      { code: "62", direction: "credit", description: "Unpaid postal order" },
      {
        code: "64",
        direction: "credit",
        description: "Transfer to your account",
        comment: "Intracompany",
      },
      {
        code: "66",
        direction: "credit",
        description: "Financial centralization",
        comment:
          "In case of centralisation by the bank, type 2 will be allotted to this transaction. This total can be followed by the detailed movement.",
      },
      { code: "87", direction: "credit", description: "Reimbursement of costs" },
      { code: "90-98", direction: "credit", description: "Codes proper to each bank" },
      { code: "99", direction: "credit", description: "Cancellation or correction" },
    ],
  },
  {
    code: "02",
    name: "Instant SEPA credit transfers",
    transactions: [
      {
        code: "01",
        direction: "debit",
        description: "Individual transfer order",
        comment: "Credit transfer given by the customer.",
      },
      {
        code: "02",
        direction: "debit",
        description: "Individual transfer order initiated by the bank",
        comment: "The bank takes the initiative for debiting the customer's account.",
      },
      {
        code: "03",
        direction: "debit",
        description: "Standing order",
        comment:
          "Credit transfer for which the order has been given once and which is carried out again at regular intervals without any change.",
      },
      {
        code: "05",
        direction: "debit",
        description: "Payment of wages, etc.",
        comment: "The principal will be debited for the total amount of the file entered.",
      },
      {
        code: "07",
        direction: "debit",
        description: "Collective transfer",
        comment: "The principal will be debited for the total amount of the file entered.",
      },
      {
        code: "13",
        direction: "debit",
        description: "Transfer from your account",
        comment:
          "Transfer from one account to another account of the same customer at the bank's or the customer's initiative (intracompany).",
      },
      {
        code: "17",
        direction: "debit",
        description: "Financial centralisation",
        comment:
          "In case of centralisation by the bank, type 2 will be allotted to this transaction. This total can be followed by the detailed movement.",
      },
      { code: "37", direction: "debit", description: "Costs" },
      { code: "40-48", direction: "debit", description: "Codes proper to each bank" },
      { code: "49", direction: "debit", description: "Cancellation or correction" },
      { code: "50", direction: "credit", description: "Transfer in your favour" },
      {
        code: "51",
        direction: "credit",
        description: "Transfer in your favour - initiated by the bank",
        comment: "The bank takes the initiative for crediting the customer's account.",
      },
      {
        code: "52",
        direction: "credit",
        description: "Payment in your favour",
        comment: "Payment by a third person",
      },
      { code: "54", direction: "credit", description: "Unexecutable transfer order" },
      {
        code: "64",
        direction: "credit",
        description: "Transfer to your account",
        comment: "Intracompany",
      },
      {
        code: "66",
        direction: "credit",
        description: "Financial centralization",
        comment:
          "In case of centralisation by the bank, type 2 will be allotted to this transaction. This total can be followed by the detailed movement.",
      },
      { code: "87", direction: "credit", description: "Reimbursement of costs" },
      { code: "90-98", direction: "credit", description: "Codes proper to each bank" },
      { code: "99", direction: "credit", description: "Cancellation or correction" },
    ],
  },
  {
    code: "03",
    name: "Cheques",
    transactions: [
      { code: "01", direction: "debit", description: "Payment of your cheque" },
      {
        code: "05",
        direction: "debit",
        description: "Payment of voucher",
        comment: "Payment of holiday pay, etc.",
      },
      { code: "09", direction: "debit", description: "Unpaid voucher" },
      { code: "11", direction: "debit", description: "Department store cheque" },
      {
        code: "15",
        direction: "debit",
        description: "Your purchase bank cheque",
        comment: "Cheque drawn by the bank on itself, usually with charges.",
      },
      {
        code: "17",
        direction: "debit",
        description: "Your certified cheque",
        comment: "Amount of the cheque; if any, charges receive code 37",
      },
      { code: "37", direction: "debit", description: "Cheque-related costs" },
      { code: "38", direction: "debit", description: "Provisionally unpaid" },
      { code: "40-48", direction: "debit", description: "Codes proper to each bank" },
      { code: "49", direction: "debit", description: "Cancellation or correction" },
      {
        code: "52",
        direction: "credit",
        description:
          "First credit of cheques, vouchers, luncheon vouchers, postal orders, credit under usual reserve",
      },
      {
        code: "58",
        direction: "credit",
        description: "Remittance of cheques, vouchers, etc. credit after collection",
        comment:
          "Also for vouchers, postal orders, anything but bills of exchange, acquittances, promissory notes, etc.",
      },
      { code: "60", direction: "credit", description: "Reversal of voucher" },
      {
        code: "62",
        direction: "credit",
        description: "Reversal of cheque",
        comment:
          "cheques debited on account, but debit cancelled afterwards for lack of cover (double debit/contra-entry of transaction 01 or 05)",
      },
      { code: "63", direction: "credit", description: "Second credit of unpaid cheque" },
      {
        code: "66",
        direction: "credit",
        description: "Remittance of cheque by your branch - credit under usual reserve",
      },
      {
        code: "87",
        direction: "credit",
        description: "Reimbursement of cheque-related costs",
        comment: "Overall amount, VAT included",
      },
      { code: "90-98", direction: "credit", description: "Codes proper to each bank" },
      { code: "99", direction: "credit", description: "Cancellation or correction" },
    ],
  },
  {
    code: "04",
    name: "Cards",
    transactions: [
      {
        code: "01",
        direction: "debit",
        description: "Loading a GSM card",
        comment: "Debit customer who is loading",
      },
      {
        code: "02",
        direction: "debit",
        description: "Payment by means of a payment card within the Eurozone",
        comment: "Eurozone = countries which have the euro as their official currency",
      },
      {
        code: "03",
        direction: "debit",
        description: "Settlement credit cards",
        comment: "See annexe III : communication 124",
      },
      {
        code: "04",
        direction: "debit",
        description: "Cash withdrawal from an ATM",
        comment: "At home as well as abroad",
      },
      { code: "05", direction: "debit", description: "Loading Proton" },
      { code: "06", direction: "debit", description: "Payment with tank card" },
      { code: "07", direction: "debit", description: "Payment by GSM" },
      {
        code: "08",
        direction: "debit",
        description: "Payment by means of a payment card outside the Eurozone",
        comment: "Eurozone = countries which have the euro as their official currency",
      },
      { code: "09", direction: "debit", description: "Upload of prepaid card" },
      { code: "10", direction: "debit", description: "Correction for prepaid card" },
      {
        code: "37",
        direction: "debit",
        description: "Costs",
        comment: "Various costs for possessing or using a payment card",
      },
      { code: "40-48", direction: "debit", description: "Codes proper to eachy bank" },
      { code: "49", direction: "debit", description: "Cancellation or correction" },
      {
        code: "50",
        direction: "credit",
        description: "Credit after a payment at a terminal",
        comment: "Except Proton",
      },
      { code: "51", direction: "credit", description: "Unloading Proton" },
      {
        code: "52",
        direction: "credit",
        description: "Loading GSM cards",
        comment: "Credit provider",
      },
      { code: "53", direction: "credit", description: "Cash deposit at an ATM" },
      { code: "54", direction: "credit", description: "Download of prepaid card" },
      { code: "55", direction: "credit", description: "Income from payments by GSM" },
      { code: "56", direction: "credit", description: "Correction for prepaid card" },
      { code: "68", direction: "credit", description: "Credit after Proton payments" },
      { code: "87", direction: "credit", description: "Reimbursement of costs" },
      { code: "90-98", direction: "credit", description: "Codes proper to each bank" },
      { code: "99", direction: "credit", description: "Cancellation or correction" },
    ],
  },
  {
    code: "05",
    name: "Direct debit",
    transactions: [
      { code: "01", direction: "debit", description: "Payment" },
      { code: "03", direction: "debit", description: "Unpaid debt" },
      { code: "05", direction: "debit", description: "Reimbursement" },
      { code: "37", direction: "debit", description: "Costs" },
      { code: "40-48", direction: "debit", description: "Codes proper to each institution" },
      { code: "49", direction: "debit", description: "Cancellation or correction" },
      { code: "50", direction: "credit", description: "Credit after collection" },
      { code: "52", direction: "credit", description: "Credit under usual reserve" },
      { code: "54", direction: "credit", description: "Reimbursement" },
      { code: "56", direction: "credit", description: "Unexecutable reimbursement" },
      {
        code: "58",
        direction: "credit",
        description: "Reversal",
        comment:
          "(cancellation of an undue debit of the debtor at the initiative of the financial institution or the debtor for lack of cover)",
      },
      { code: "87", direction: "credit", description: "Reimbursement of costs" },
      { code: "90-98", direction: "credit", description: "Codes proper to each bank" },
      { code: "99", direction: "credit", description: "Cancellation or correction" },
    ],
  },
  {
    code: "07",
    name: "Domestic commercial paper",
    transactions: [
      {
        code: "01",
        direction: "debit",
        description: "Payment commercial paper",
        comment: "Bills of exchange, acquittances, promissory notes; debit of the drawee",
      },
      {
        code: "05",
        direction: "debit",
        description: "Commercial paper claimed back",
        comment:
          "Bill claimed back at the drawer's request (bill claimed back before maturity date)",
      },
      {
        code: "06",
        direction: "debit",
        description: "Extension of maturity date",
        comment: "Costs chargeable to the remitter",
      },
      {
        code: "07",
        direction: "debit",
        description: "Unpaid commercial paper",
        comment: "Contra-entry of a direct credit or of a discount",
      },
      {
        code: "08",
        direction: "debit",
        description: "Payment in advance",
        comment:
          "Debit of the remitter when the drawee pays in advance directly to the remitter (regards bank acceptances)",
      },
      {
        code: "09",
        direction: "debit",
        description: "Agio on supplier's bill",
        comment: "Debit of the agios to the account of the drawee",
      },
      {
        code: "37",
        direction: "debit",
        description: "Costs related to commercial paper",
        comment: "If any, detail in the category (e.g. costs for presentation for acceptance, etc.)",
      },
      {
        code: "39",
        direction: "debit",
        description: "Return of an irregular bill of exchange",
        comment: "Debit of the drawer after credit under usual reserve or discount",
      },
      { code: "40-48", direction: "debit", description: "Codes proper to each bank" },
      { code: "49", direction: "debit", description: "Cancellation or correction" },
      {
        code: "50",
        direction: "credit",
        description: "Remittance of commercial paper - credit after collection",
        comment: "Credit of the remitter",
      },
      {
        code: "52",
        direction: "credit",
        description: "Remittance of commercial paper - credit under usual reserve",
      },
      {
        code: "54",
        direction: "credit",
        description: "Remittance of commercial paper for discount",
        comment: "Among other things advances or promissory notes",
      },
      {
        code: "56",
        direction: "credit",
        description: "Remittance of supplier's bill with guarantee",
      },
      {
        code: "58",
        direction: "credit",
        description: "Remittance of supplier's bill without guarantee",
      },
      { code: "87", direction: "credit", description: "Reimbursement of costs" },
      { code: "90-98", direction: "credit", description: "Codes proper to each bank" },
      { code: "99", direction: "credit", description: "Cancellation or correction" },
    ],
  },
  {
    code: "09",
    name: "Counter transactions",
    transactions: [
      {
        code: "01",
        direction: "debit",
        description: "Cash withdrawal",
        comment: "Withdrawal by counter cheque or receipt; cash remitted by the bank clerk",
      },
      { code: "05", direction: "debit", description: "Purchase of foreign bank notes" },
      { code: "07", direction: "debit", description: "Purchase of gold/pieces" },
      { code: "09", direction: "debit", description: "Purchase of petrol coupons" },
      {
        code: "13",
        direction: "debit",
        description: "Cash withdrawal by your branch or agents",
        comment: "On the account of the head office",
      },
      { code: "17", direction: "debit", description: "Purchase of fiscal stamps" },
      {
        code: "19",
        direction: "debit",
        description: "Difference in payment",
        comment:
          "Used in case of payments accepted under reserve of count, result of overcrediting",
      },
      { code: "25", direction: "debit", description: "Purchase of traveller's cheque" },
      { code: "37", direction: "debit", description: "Costs" },
      { code: "40-48", direction: "debit", description: "Codes proper to each bank" },
      { code: "49", direction: "debit", description: "Cancellation or correction" },
      {
        code: "50",
        direction: "credit",
        description: "Cash payment",
        comment:
          "For own account - the comment for the client is given in the communication; also for mixed payments (cash + cheques) - not to be communicated to the clients; for payments made by a third person: see family 01",
      },
      { code: "52", direction: "credit", description: "Payment night safe" },
      {
        code: "58",
        direction: "credit",
        description: "Payment by your branch/agents",
        comment:
          "Takes priority over transaction 52 (hence a payment made by an agent in a night safe = 58 and not 52)",
      },
      { code: "60", direction: "credit", description: "Sale of foreign bank notes" },
      { code: "62", direction: "credit", description: "Sale of gold/pieces under usual reserve" },
      {
        code: "68",
        direction: "credit",
        description: "Difference in payment",
        comment:
          "In case of payment accepted under reserve of count; result of undercrediting - see also transaction 19",
      },
      { code: "70", direction: "credit", description: "Sale of traveller's cheque" },
      { code: "87", direction: "credit", description: "Reimbursement of costs" },
      { code: "90-98", direction: "credit", description: "Codes proper to each bank" },
      { code: "99", direction: "credit", description: "Cancellation or correction" },
    ],
  },
  {
    code: "11",
    name: "Securities",
    transactions: [
      {
        code: "01",
        direction: "debit",
        description: "Purchase of securities",
        comment:
          "Purchase of domestic or foreign securities, including subscription rights, certificates, etc.",
      },
      {
        code: "02",
        direction: "debit",
        description: "Tenders",
        comment: "Payment to the bank on maturity date",
      },
      {
        code: "03",
        direction: "debit",
        description: "Subscription to securities",
        comment: "Bonds, shares, tap issues of CDs, with or without payment of interest, etc.",
      },
      { code: "04", direction: "debit", description: "Issues" },
      {
        code: "05",
        direction: "debit",
        description: "Partial payment subscription",
        comment: "Debit of the subscriber for the complementary payment of partly-paid shares",
      },
      {
        code: "06",
        direction: "debit",
        description: "Share option plan - exercising an option",
      },
      {
        code: "09",
        direction: "debit",
        description: "Settlement of securities",
        comment:
          "For professionals (stockbrokers) only, whoever the issuer may be (Belgian or foreigner)",
      },
      {
        code: "11",
        direction: "debit",
        description: "Payable coupons/repayable securities",
        comment: "Debit of the issuer by the bank in charge of the financial service",
      },
      {
        code: "13",
        direction: "debit",
        description: "Your repurchase of issue",
        comment: "Unissued part (see 64)",
      },
      {
        code: "15",
        direction: "debit",
        description: "Interim interest on subscription",
        comment: "In case of subscription before the interest due date",
      },
      { code: "17", direction: "debit", description: "Management fee" },
      { code: "19", direction: "debit", description: "Regularisation costs" },
      { code: "37", direction: "debit", description: "Costs" },
      { code: "40-48", direction: "debit", description: "Codes proper to each bank" },
      { code: "49", direction: "debit", description: "Cancellation or correction" },
      { code: "50", direction: "credit", description: "Sale of securities" },
      {
        code: "51",
        direction: "credit",
        description: "Tender",
        comment: "Company issues paper in return for cash",
      },
      {
        code: "52",
        direction: "credit",
        description:
          "Payment of coupons from a deposit or settlement of coupons delivered over the counter - credit under usual reserve",
        comment: "Whatever the currency of the security",
      },
      {
        code: "58",
        direction: "credit",
        description:
          "Repayable securities from a deposit or delivered at the counter - credit under usual reserve",
      },
      {
        code: "62",
        direction: "credit",
        description: "Interim interest on subscription",
        comment: "When reimbursed separately to the subscriber",
      },
      {
        code: "64",
        direction: "credit",
        description: "Your issue",
        comment:
          "Amount paid to the issuer by the bank in charge of the placement (firm underwriting or not); also used for the payment in full of partly-paid shares, see transaction 05",
      },
      {
        code: "66",
        direction: "credit",
        description: "Retrocession of issue commission",
        comment: "For professionals such as insurances and stockbrokers",
      },
      {
        code: "68",
        direction: "credit",
        description: "Compensation for missing coupon",
        comment: "In case coupons attached to a purchased security are missing",
      },
      {
        code: "70",
        direction: "credit",
        description: "Settlement of securities",
        comment: "Only with stockbrokers when they deliver the securities to the bank",
      },
      { code: "87", direction: "credit", description: "Reimbursement of costs" },
      { code: "90-98", direction: "credit", description: "Codes proper to each bank" },
      { code: "99", direction: "credit", description: "Cancellation or correction" },
    ],
  },
  {
    code: "13",
    name: "Credits",
    transactions: [
      {
        code: "01",
        direction: "debit",
        description: "Short-term loan",
        comment: "Capital and/or interest (specified by the category)",
      },
      { code: "02", direction: "debit", description: "Long-term loan" },
      {
        code: "05",
        direction: "debit",
        description: "Settlement of fixed advance",
        comment: "Full or partial reimbursement of a fixed advance at maturity date",
      },
      {
        code: "07",
        direction: "debit",
        description: "Your repayment instalment credits",
        comment:
          "Often by standing order or direct debit. In case of direct debit, family 13 is used.",
      },
      { code: "11", direction: "debit", description: "Your repayment mortgage loan" },
      { code: "13", direction: "debit", description: "Settlement of bank acceptances" },
      {
        code: "15",
        direction: "debit",
        description: "Your repayment hire-purchase and similar claims",
        comment: "Hire-purchase agreement under which the financial institution is the lessor",
      },
      { code: "19", direction: "debit", description: "Documentary import credits" },
      { code: "21", direction: "debit", description: "Other credit applications" },
      { code: "37", direction: "debit", description: "Credit-related costs" },
      { code: "40-48", direction: "debit", description: "Codes proper to each bank" },
      { code: "49", direction: "debit", description: "Cancellation or correction" },
      { code: "50", direction: "credit", description: "Settlement of instalment credit" },
      { code: "54", direction: "credit", description: "Fixed advance - capital and interest" },
      { code: "55", direction: "credit", description: "Fixed advance - interest only" },
      {
        code: "56",
        direction: "credit",
        description: "Subsidy",
        comment: "Interest or capital subsidy",
      },
      { code: "60", direction: "credit", description: "Settlement of mortgage loan" },
      { code: "62", direction: "credit", description: "Term loan" },
      { code: "68", direction: "credit", description: "Documentary export credits" },
      { code: "70", direction: "credit", description: "Settlement of discount bank acceptance" },
      { code: "87", direction: "credit", description: "Reimbursement of costs" },
      { code: "90-98", direction: "credit", description: "Codes proper to each bank" },
      { code: "99", direction: "credit", description: "Cancellation or correction" },
    ],
  },
  {
    code: "30",
    name: "Miscellaneous transactions",
    transactions: [
      { code: "01", direction: "debit", description: "Spot purchase of foreign exchange" },
      { code: "03", direction: "debit", description: "Forward purchase of foreign exchange" },
      { code: "05", direction: "debit", description: "Capital and/or interest term investment" },
      { code: "33", direction: "debit", description: "Value (date) correction" },
      { code: "37", direction: "debit", description: "Costs" },
      { code: "39", direction: "debit", description: "Undefined transaction" },
      { code: "40-48", direction: "debit", description: "Codes proper to each bank" },
      { code: "49", direction: "debit", description: "Cancellation or correction" },
      { code: "50", direction: "credit", description: "Spot sale of foreign exchange" },
      { code: "52", direction: "credit", description: "Forward sale of foreign exchange" },
      { code: "54", direction: "credit", description: "Capital and/or interest term investment" },
      { code: "55", direction: "credit", description: "Interest term investment" },
      { code: "83", direction: "credit", description: "Value (date) correction" },
      { code: "87", direction: "credit", description: "Reimbursement of costs" },
      { code: "89", direction: "credit", description: "Undefined transaction" },
      { code: "90-98", direction: "credit", description: "Codes proper to each bank" },
      { code: "99", direction: "credit", description: "Cancellation or correction" },
    ],
  },
  {
    code: "35",
    name: "Closing (e.g. periodical payments of interest, costs, ...)",
    transactions: [
      { code: "01", direction: "debit", description: "Closing" },
      { code: "37", direction: "debit", description: "Costs" },
      { code: "40-48", direction: "debit", description: "Codes proper to each bank" },
      { code: "49", direction: "debit", description: "Cancellation or correction" },
      { code: "50", direction: "credit", description: "Closing" },
      { code: "87", direction: "credit", description: "Reimbursement of costs" },
      { code: "90-98", direction: "credit", description: "Codes proper to each bank" },
      { code: "99", direction: "credit", description: "Cancellation or correction" },
    ],
  },
  {
    code: "41",
    name: "Foreign - non-SEPA credit transfers",
    transactions: [
      { code: "01", direction: "debit", description: "Transfer" },
      { code: "03", direction: "debit", description: "Standing order" },
      { code: "05", direction: "debit", description: "Collective payments of wages" },
      { code: "07", direction: "debit", description: "Collective transfers" },
      {
        code: "13",
        direction: "debit",
        description: "Transfer from your account",
        comment: "Intracompany",
      },
      { code: "17", direction: "debit", description: "Financial centralisation (debit)" },
      {
        code: "37",
        direction: "debit",
        description: "Costs relating to outgoing foreign transfers and non-SEPA transfers",
      },
      {
        code: "38",
        direction: "debit",
        description: "Costs relating to incoming foreign and non-SEPA transfers",
      },
      { code: "40-48", direction: "debit", description: "Codes proper to each bank" },
      { code: "49", direction: "debit", description: "Cancellation or correction" },
      { code: "50", direction: "credit", description: "Transfer" },
      {
        code: "64",
        direction: "credit",
        description: "Transfer to your account",
        comment: "Intracompany",
      },
      { code: "66", direction: "credit", description: "Financial centralisation (credit)" },
      { code: "87", direction: "credit", description: "Reimbursement of costs" },
      { code: "90-98", direction: "credit", description: "Codes proper to each bank" },
      { code: "99", direction: "credit", description: "Cancellation or correction" },
    ],
  },
  {
    code: "43",
    name: "Foreign cheques",
    transactions: [
      {
        code: "01",
        direction: "debit",
        description: "Payment of a foreign cheque",
        comment: "Debit of a cheque in foreign currency or in EUR in favour of a foreigner",
      },
      {
        code: "07",
        direction: "debit",
        description: "Unpaid foreign cheque",
        comment: "Foreign cheque remitted for collection that returns unpaid",
      },
      { code: "15", direction: "debit", description: "Purchase of an international bank cheque" },
      { code: "37", direction: "debit", description: "Costs relating to payment of foreign cheques" },
      { code: "40-48", direction: "debit", description: "Codes proper to each bank" },
      { code: "49", direction: "debit", description: "Cancellation or correction" },
      {
        code: "52",
        direction: "credit",
        description: "Remittance of foreign cheque credit under usual reserve",
      },
      {
        code: "58",
        direction: "credit",
        description: "Remittance of foreign cheque credit after collection",
      },
      { code: "62", direction: "credit", description: "Reversal of cheques" },
      { code: "87", direction: "credit", description: "Reimbursement of costs" },
      { code: "90-98", direction: "credit", description: "Codes proper to each bank" },
      { code: "99", direction: "credit", description: "Cancellation or correction" },
    ],
  },
  {
    code: "47",
    name: "Foreign commercial paper",
    transactions: [
      { code: "01", direction: "debit", description: "Payment of foreign bill" },
      { code: "05", direction: "debit", description: "Bill claimed back" },
      { code: "06", direction: "debit", description: "Extension" },
      { code: "07", direction: "debit", description: "Unpaid foreign bill" },
      {
        code: "11",
        direction: "debit",
        description: "Payment documents abroad",
        comment: "Bills of lading",
      },
      {
        code: "13",
        direction: "debit",
        description: "Discount foreign supplier's bills",
        comment: "Debit customer, payment of agios, interest, exchange commission, etc.",
      },
      { code: "14", direction: "debit", description: "Warrant fallen due" },
      {
        code: "37",
        direction: "debit",
        description: "Costs relating to the payment of a foreign bill",
      },
      { code: "40-48", direction: "debit", description: "Codes proper to each bank" },
      { code: "49", direction: "debit", description: "Cancellation or correction" },
      {
        code: "50",
        direction: "credit",
        description: "Remittance of foreign bill credit after collection",
      },
      {
        code: "52",
        direction: "credit",
        description: "Remittance of foreign bill credit under usual reserve",
      },
      { code: "54", direction: "credit", description: "Discount abroad" },
      {
        code: "56",
        direction: "credit",
        description: "Remittance of guaranteed foreign supplier's bill",
      },
      { code: "58", direction: "credit", description: "Idem without guarantee" },
      {
        code: "60",
        direction: "credit",
        description: "Remittance of documents abroad - credit under usual reserve",
      },
      {
        code: "62",
        direction: "credit",
        description: "Remittance of documents abroad - credit after collection",
      },
      { code: "64", direction: "credit", description: "Warrant" },
      { code: "87", direction: "credit", description: "Reimbursement of costs" },
      { code: "90-98", direction: "credit", description: "Codes proper to each bank" },
      { code: "99", direction: "credit", description: "Cancellation or correction" },
    ],
  },
  {
    code: "80",
    name: "Fees and commissions charged separately",
    transactions: [
      { code: "02", direction: "debit", description: "Costs relating to electronic output" },
      { code: "04", direction: "debit", description: "Costs for holding a documentary cash credit" },
      { code: "06", direction: "debit", description: "Damage relating to bills and cheques" },
      {
        code: "07",
        direction: "debit",
        description: "Insurance costs",
        comment:
          "- insurance costs of account holders against fatal accidents - passing-on of several insurance costs",
      },
      { code: "08", direction: "debit", description: "Registering compensation for savings accounts" },
      {
        code: "09",
        direction: "debit",
        description: "Postage",
        comment: "Postage recouped to the debit of the customer (including forwarding charges)",
      },
      { code: "10", direction: "debit", description: "Purchase of Smartcard" },
      {
        code: "11",
        direction: "debit",
        description: "Costs for the safe custody of correspondence",
        comment:
          "Costs chargeable to clients who ask to have their correspondence kept at their disposal at the bank's counter",
      },
      { code: "12", direction: "debit", description: "Costs for opening a bank guarantee" },
      {
        code: "13",
        direction: "debit",
        description: "Renting of safes",
        comment: "Commission for renting a safe deposit box",
      },
      { code: "14", direction: "debit", description: "Handling costs instalment credit" },
      {
        code: "15",
        direction: "debit",
        description: "Night safe",
        comment:
          "Commission collected to the debit of the customer to whom the bank delivers a key which gives access to the night safe",
      },
      { code: "16", direction: "debit", description: "Bank confirmation to revisor or accountant" },
      {
        code: "17",
        direction: "debit",
        description: "Charge for safe custody",
        comment: "Collected for unsealed deposit of securities, and other parcels",
      },
      { code: "18", direction: "debit", description: "Trade information" },
      {
        code: "19",
        direction: "debit",
        description: "Special charge for safe custody",
        comment: "Collected for securities, gold, pass-books, etc. placed in safe custody",
      },
      { code: "20", direction: "debit", description: "Drawing up a certificate" },
      {
        code: "21",
        direction: "debit",
        description: "Pay-packet charges",
        comment: "Charges for preparing pay packets",
      },
      { code: "22", direction: "debit", description: "Management/custody" },
      {
        code: "23",
        direction: "debit",
        description: "Research costs",
        comment:
          "Costs charged for all kinds of research (information on past transactions, address retrieval, ...)",
      },
      {
        code: "24",
        direction: "debit",
        description: "Participation in and management of interest refund system",
      },
      {
        code: "25",
        direction: "debit",
        description: "Renting of direct debit box",
        comment: "Commission for the renting of boxes put at the disposal for the correspondence",
      },
      { code: "26", direction: "debit", description: "Travel insurance premium" },
      {
        code: "27",
        direction: "debit",
        description: "Subscription fee",
        comment: "For publications of the financial institution",
      },
      {
        code: "29",
        direction: "debit",
        description: "Information charges",
        comment: "Charges collected for: - commercial information - sundry information",
      },
      {
        code: "31",
        direction: "debit",
        description: "Writ service fee",
        comment: "E.g. for signing invoices",
      },
      {
        code: "33",
        direction: "debit",
        description: "Miscellaneous fees and commissions",
        comment:
          "Costs not specified otherwise, often with a manual communication (e.g. for collecting, ordering funds). VAT excluded = type 0 VAT included = type 3 (at least 3 articles)",
      },
      {
        code: "35",
        direction: "debit",
        description: "Costs",
        comment: "Costs charged for calculating the amount of the tax to be paid (e.g. Fiscomat).",
      },
      {
        code: "37",
        direction: "debit",
        description: "Access right to database",
        comment: 'Fixed right, either one-off or periodical; for details, see "categories"',
      },
      {
        code: "39",
        direction: "debit",
        description: "Surety fee",
        comment: "Agios on guarantees given",
      },
      { code: "41", direction: "debit", description: "Research costs" },
      { code: "43", direction: "debit", description: "Printing of forms" },
      { code: "45", direction: "debit", description: "Documentary credit charges" },
      { code: "47", direction: "debit", description: "Charging fees for transactions" },
      { code: "49", direction: "debit", description: "Cancellation or correction" },
      { code: "99", direction: "credit", description: "Cancellation or correction" },
    ],
  },
];

// Category codes (positions 6-8 of the 8-digit code). The category provides the detail of
// the charges or of the settlement of fees and commissions; for ordinary single entries it
// is normally "000". Categories 700-999 are proper to each bank. Where the spec lists
// several labels under one code, they are joined with " / ".
export const CODA_CATEGORIES: Record<string, string> = {
  "000": "Net amount",
  "001": "Interest received",
  "002": "Interest paid",
  "003": "Credit commission",
  "004": "Postage",
  "005": "Renting of letterbox",
  "006": "Various fees/commissions",
  "007": "Access right to database",
  "008": "Information charges",
  "009": "Travelling expenses",
  "010": "Writ service fee",
  "011": "VAT",
  "012": "Exchange commission",
  "013": "Payment commission",
  "014": "Collection commission",
  "015": "Correspondent charges",
  "016": "Negative interest",
  "017": "Research costs",
  "018": "Tental guarantee charges",
  "019": "Tax on physical delivery",
  "020": "Costs of physical delivery",
  "021": "Costs for drawing up a bank cheque",
  "022": "Priority costs",
  "023": "Exercising fee",
  "024": "Growth premium",
  "025": "Individual entry for exchange charges",
  "026": "Handling commission",
  "027": "Charges for unpaid bills",
  "028": "Fidelity premium",
  "029": "Protest charges",
  "030": "Account insurance",
  "031": "Charges foreign cheque",
  "032": "Drawing up a circular cheque",
  "033": "Charges for a foreign bill",
  "034": "Reinvestment fee",
  "035": "Charges foreign documentary bill",
  "036": "Costs relating to a refused cheque",
  "037": "Commission for handling charges",
  "039": "Telecommunications",
  "041": "Credit card costs",
  "042": "Payment card costs",
  "043": "Insurance costs",
  "045": "Handling costs",
  "047": "Charges extension bill",
  "049": "Fiscal stamps/stamp duty",
  "050": "Capital term investment",
  "051": "Withholding tax",
  "053": "Printing of forms",
  "055": "Repayment loan or credit capital",
  "057": "Interest subsidy",
  "058": "Capital premium",
  "059": "Default interest",
  "061": "Charging fees for transactions",
  "063": "Rounding differences",
  "065": "Interest payment advice",
  "066": "Fixed loan advance - reimbursement",
  "067": "Fixed loan advance - extension",
  "068": "Countervalue of an entry",
  "069": "Forward arbitrage contracts : sum to be supplied by customer",
  "070": "Forward arbitrage contracts : sum to be supplied by bank",
  "071": "Fixed loan advance - availability",
  "072": "Countervalue of commission to third party",
  "073": "Costs of ATM abroad",
  "074": "Mailing costs",
  "100": "Gross amount",
  "200": "Overall documentary credit charges",
  "201": "Advice notice commission",
  "202": "Advising commission / Additional advising commission",
  "203":
    "Confirmation fee / Additional confirmation fee / Commitment fee / Flat fee / Confirmation reservation commission / Additional reservation commission",
  "204": "Amendment fee",
  "205":
    "Documentary payment commission / Document commission / Drawdown fee / Negotiation fee",
  "206": "Surety fee/payment under reserve",
  "207": "Non-conformity fee",
  "208": "Commitment fee deferred payment",
  "209": "Transfer commission",
  "210": "Commitment fee",
  "211": "Credit arrangement fee / Additional credit arrangement fee",
  "212": "Warehousing fee",
  "213": "Financing fee",
  "214": "Issue commission (delivery order)",
  "400": "Acceptance fee",
  "401": "Visa charges",
  "402": "Certification costs",
  "403": "Minimum discount rate",
  "404": "Discount commission",
  "405": "Bill guarantee commission",
  "406": "Collection charges",
  "407": "Costs Article 45",
  "408": "Cover commission",
  "409": "Safe deposit charges",
  "410": "Reclamation charges",
  "411": "Fixed collection charge",
  "412": "Advice of expiry charges",
  "413": "Acceptance charges",
  "414": "Regularisation charges",
  "415": "Surety fee",
  "416": "Charges for the deposit of security",
  "418": "Endorsement commission",
  "419": "Bank service fee",
  "420": "Retention charges",
  "425": "Foreign broker's commission",
  "426": "Belgian broker's commission",
  "427": "Belgian Stock Exchange tax",
  "428": "Interest accrued",
  "429": "Foreign Stock Exchange tax",
  "430": "Recovery of foreign tax",
  "431": "Delivery of a copy",
  "435": "Tax on physical securities",
  "436": "Supplimentary tax",
  "437": "Speculation tax",
  "438": "Securities account tax",
};
